### ISSUE TITLE
option keyword not working with BifConst

### ISSUE THREAD

**Issue by grigorescu** [bro/bro#202]
I went through our scripts to identify what variables we're currently redef-ing, in order to convert those to use the new option keyword. It looks like any variable that's accessed via BifConst results in an error when it's converted to an option.

For example, SMB::pipe_filenames is accessed via BifConst here:

`smb2-com-create.pac:               BifConst::SMB::pipe_filenames->AsTable()->Lookup(filename->CheckString()) )`

And when I change the export block in init-bare to:

`option SMB::pipe_filenames: set[string] = {};`

I get the following error:

`internal error: internal variable SMB::pipe_filenames is not constant`

Is there something intrinsically different about variables that are accessed via BifConst, or can this behavior be fixed?

**Comment by grigorescu** [comment]
I think I was chasing a bit of a red herring. It's not that these are accessed via BifConst, it's that they're defined in .bif files.

For instance, use_conn_size_analyzer is never accessed directly (frankly, I'm not sure that particular option does anything), but the same error occurs when changing it to an option.

**Comment by jsiwek** [comment]
This seems intentional, or at least should not be changed IMO.

I can't think of a legit reason for the BIF-layer to provide this same type of Val access for options in the same way it does for consts.  That's because option Val's are intended to be mutated/replaced at runtime such that doing a one-time ID lookup upon initialization won't work as expected if that ID's Val ever gets replaced by the config framework later.

So the path to making `SMB::pipe_filenames` an `option` is rather to remove its .bif declaration and update any smb .pac files that were using BifConst to access it to instead dynamically look up the ID at runtime and use its current value.

**Comment by grigorescu** [comment]
Yeah, that makes sense, and I think I agree.

On a lark, I "fixed" the error by doing this:

```
diff --git a/src/Var.cc b/src/Var.cc
index d4659023a..8745f9e89 100644
--- a/src/Var.cc
+++ b/src/Var.cc
@@ -529,7 +529,7 @@ Val* internal_const_val(const char* name)
        if ( ! id )
                reporter->InternalError("internal variable %s missing", name);

-       if ( ! id->IsConst() )
+       if ( ! ( id->IsConst() || id->IsOption() ) )
                reporter->InternalError("internal variable %s is not constant", name);

        Val* rval = id->ID_Val();
```

All the tests pass; I'm just not sure that actually modifying these values at runtime is the correct behavior. If these aren't getting reread/updated, that breaks the user's expectations.

I think the decision of what's defined in the BIF-layer and what isn't needs to be fleshed out a bit more, as you said.
