### ISSUE TITLE
Missing ICMP counterpart entry for router solicitation/advertisement?

### ISSUE THREAD

**Issue by ckreibich** [bro/bro#218]
Over in Community ID land @simonemainardi has submitted this issue: https://github.com/corelight/community-id-spec/issues/2

I think it correctly points out that the ICMP_ROUTERADVERT -> ICMP_ROUTERSOLICIT direction is missing, and since this code is directly mirrored on Zeek's I'm thinking there's an omission here too. Thoughts?

https://github.com/bro/bro/blob/master/src/analyzer/protocol/icmp/ICMP.cc#L865

**Comment by jsiwek** [comment]
Thanks, I added the missing counterpart in `master` now and will be in 2.6.

Not quite sure if it was originally intentional with the thought being that advertisements may be one-way in the sense that they are sent periodically even when not in response to a solicitation, but I think it makes sense to change now for reasons (1) ICMPv6 counterparts code did include advertisement/solicitation pairs, so this makes ICMPv4 consistent with that (2) we don't lose any information by changing this code path as advertisement/solicitation messages have well-known code=0, so better to return counterpart rather than code and (3) the change in "one-way" flag only potentially changes hash-key calculation for connection lookups and I don't think that matters here
