### ISSUE TITLE
TCP events

### ISSUE THREAD

**Issue by georgiaxron** [bro/bro#222]
Hello,
i am using bro's usr/share/bro/base/bif/plugins/Bro_TCT.events.bif.bro script in order to have an image of the tcp events that are beeing logged during my capture. Is there any other way to have those exports as pcap and not as raw data? If i use the -w option i have an entire pcap image of my capture and i dont want that. Is the only solution to write a script of my own?
Thanks in advance

**Comment by jsiwek** [comment]
You may need to clarify, since you seem to want pcap output, but then also don't want pcap output from `-w`, then I don't quite understand what format you actually do want.  If you want to filter only certain connections in the pcap output, that's possible: use the `-f` command line option and/or or see the packet-filter scripts.

Also, GitHub issues are more for tracking bugs and feature requests, so this type of support question may get more feedback if you send it to the mailing list:

http://mailman.icsi.berkeley.edu/mailman/listinfo/bro

**Comment by hosom** [comment]
Responding here, just because it is most likely that @georgiaxron will see it here. 

They may be looking for [dump_current_packet(file_name: string): bool](https://www.bro.org/sphinx/scripts/base/bif/bro.bif.bro.html#id-dump_current_packet), which is a BIF that would allow a user to select a packet with an event and then dump it to disk. This function should be used with **extreme care**, and should almost certainly never be used on a production monitoring instance of Bro. 

It's also worth mentioning that these types of questions are also welcomed on IRC [http://webchat.freenode.net/?randomnick=1&channels=%23bro](http://webchat.freenode.net/?randomnick=1&channels=%23bro).

**Comment by georgiaxron** [comment]
@hosom yes this exactly what i want. Please check your email if you wish cause i send you one regarding this subject
